# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='matching',
            field=models.CharField(choices=[('FU', 'Fuzzy'), ('ST', 'Strict')], default='FU', help_text='The comparison method for checking if an answer is correct.Fuzzy matching attempts to compensate for accents, punctuation, whitespace, and spelling. If using numbers, dates, or acronyms use Strict.', max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='wordings',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[\\w ]+(?:\\,[\\w ]+)*\\Z', 32), code='invalid', message='Enter strings separated by commas.')]),
        ),
    ]
