# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Tags must consist of letters, numbers, and underscores.', max_length=30, unique=True)),
            ],
        ),
    ]
