# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tokens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(default=tokens.models.create_key, max_length=100, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', related_query_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
